basePath: /
definitions:
  domain.User:
    properties:
      id:
        type: integer
      phone:
        type: string
    type: object
  http.ErrorResponse:
    properties:
      failedField:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
  http.LoginRequest:
    properties:
      password:
        type: string
      phone:
        type: string
    required:
    - password
    - phone
    type: object
  http.LoginResponse:
    properties:
      access_token:
        type: string
      data:
        $ref: '#/definitions/domain.User'
    type: object
host: localhost:3000
info:
  contact: {}
  description: REST API for breeders zone auth service
  title: Breeders Zone Auth API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: sign in info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/http.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.LoginRequest'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.LoginRequest'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http.LoginRequest'
      summary: User Login
      tags:
      - users-auth
securityDefinitions:
  UsersAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
