basePath: /
definitions:
  domain.User:
    properties:
      companyName:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
      surname:
        type: string
      verified:
        type: boolean
    type: object
  errors.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  errors.ValidationError:
    properties:
      failedField:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
  errors.ValidationErrorResponse:
    properties:
      code:
        type: integer
      errors:
        items:
          $ref: '#/definitions/errors.ValidationError'
        type: array
      message:
        type: string
    type: object
  http.LoginRequest:
    properties:
      password:
        type: string
      phone:
        type: string
    required:
    - password
    - phone
    type: object
  http.LoginResponse:
    properties:
      access_token:
        type: string
      data:
        $ref: '#/definitions/domain.User'
    type: object
host: localhost:3000
info:
  contact: {}
  description: REST API for breeders zone auth service
  title: Breeders Zone Auth API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: sign in info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/http.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.ValidationErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http.LoginRequest'
      summary: User Login
      tags:
      - users-auth
  /oauth/{provider}:
    get:
      consumes:
      - application/json
      description: Redirect to OAuth provider
      parameters:
      - description: Oauth provider
        in: path
        name: provider
        required: true
        type: string
      responses:
        "200":
          description: ""
      summary: OAuth provider redirect
      tags:
      - oauth
  /oauth/{provider}/callback:
    get:
      consumes:
      - application/json
      description: Callback for OAuth provider
      parameters:
      - description: Oauth provider
        in: path
        name: provider
        required: true
        type: string
      responses:
        "301":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
      summary: OAuth provider callback
      tags:
      - oauth
securityDefinitions:
  UsersAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
